---
  html_document:
    toc: true
    highlight: zenburn
    theme: united
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(tidy=TRUE, highlight=TRUE, dev="png",
               cache=FALSE, highlight=TRUE, autodep=TRUE, warning=FALSE, error=FALSE,
               message=FALSE, prompt=TRUE, comment='', fig.cap='')
```

First we will load in each of the count files and make a big matrix of N rows
of genes with M columns of samples.

```{r}
stems = c("1", "3", "4", "5", "6", "12a", "14", "26")
count_files = file.path("..", "data", paste(stems, ".counts.genes", sep=""))
```

```{r}
count_reader = function(fn) {
  sample = strsplit(basename(fn), ".", fixed=TRUE)[[1]][1]
  sample = paste("sample_", sample, sep="")
  data = read.table(fn, header=FALSE, row.names=1)
  colnames(data) = c(sample)
  data
}
counts = do.call(cbind, lapply(count_files, count_reader))
colData = data.frame(sample=colnames(counts))
rownames(colData) = colData$sample
```

We plotted the most variable genes in a similar fashion to here:

http://pklab.med.harvard.edu/scw2014/subpop_tutorial.html

```{r}
library(DESeq)
lib.size = estimateSizeFactorsForMatrix(counts)
ed <- t(t(counts)/lib.size)
means <- rowMeans(ed)
vars <- apply(ed,1,var)
cv2 <- vars/means^2
par(mar=c(3.5,3.5,1,1),mgp=c(2,0.65,0),cex=0.9)
smoothScatter(log(means),log(cv2))
```

```{r}
require(statmod)
minMeanForFit <- unname( quantile( means[ which( cv2 > .3 ) ], .95 ) )
useForFit <- means >= minMeanForFit # & spikeins
fit <- glmgam.fit( cbind( a0 = 1, a1tilde = 1/means[useForFit] ),cv2[useForFit] )
a0 <- unname( fit$coefficients["a0"] )
a1 <- unname( fit$coefficients["a1tilde"])
fit$coefficients
```

```{r}
# repeat previous plot
par(mar=c(3.5,3.5,1,1),mgp=c(2,0.65,0),cex=0.9); smoothScatter(log(means),log(cv2));
xg <- exp(seq( min(log(means[means>0])), max(log(means)), length.out=1000 ))
vfit <- a1/xg + a0
# add fit line
lines( log(xg), log(vfit), col="black", lwd=3 )
df <- ncol(ed) - 1
# add confidence interval
lines(log(xg),log(vfit * qchisq(0.975,df)/df),lty=2,col="black")
lines(log(xg),log(vfit * qchisq(0.025,df)/df),lty=2,col="black")
```

```{r}
afit <- a1/means+a0
varFitRatio <- vars/(afit*means^2)
varorder <- order(varFitRatio,decreasing=T)
oed <- ed[varorder,]
# repeat previous plot
par(mar=c(3.5,3.5,1,1),mgp=c(2,0.65,0),cex=0.9); smoothScatter(log(means),log(cv2)); lines( log(xg), log(vfit), col="black", lwd=3 ); lines(log(xg),log(vfit * qchisq(0.975,df)/df),lty=2,col="black"); lines(log(xg),log(vfit * qchisq(0.025,df)/df),lty=2,col="black");
# add top 100 genes
points(log(means[varorder[1:100]]),log(cv2[varorder[1:100]]),col=2)
```

```{r}
pval <- pchisq(varFitRatio*df,df=df,lower.tail=F)
adj.pval <- p.adjust(pval,"fdr")
sigVariedGenes <- adj.pval<1e-3;
sig = ed[names(sigVariedGenes[which(sigVariedGenes)]),]
```

```{r}
write.table(rownames(sig), quote=FALSE, sep="\t", row.names=FALSE, col.names=FALSE,
            file="sig_genes.txt")
rownames(sig)
```
